---

- name: Creates tarball
  archive:
    path: "{{workdir}}"
    dest: "/dest/tmp/{{version}}.tar.gz"
  when: artefact is defined and artfeact.type == "tarball"

# Task to upload tarball to s3

# Task to create container when build_output = docker
