---

- name: Copies private key
  copy:
    dest: ~/.ssh/id_rsa
    content: "{{ ci_key |default() }}"
    state: present
    create: yes
    mode: 0400

- name: Creates checkout dir
  become: true
  file:
    path: "{{workdir}}"
    state: directory
    owner: "{{ansible_user_id}}"
    group: "{{ansible_user_gid}}"
    mode: 0755
 
- name: Checkout repo
  git:
    repo: "{{repo}}"
    dest: "{{workdir}}"
    depth: 1
    version: "{{version}}"
    key_file: ~/.ssh/id_rsa
    accept_hostkey: true
