---

- name: Checkout repo
  git:
    repo: "{{webops_build_repo}}"
    dest: "{{webops_build_workdir}}"
    depth: 1
    version: "{{webops_build_version}}"

- name: Remove git db
  file:
    path: "{{webops_build_workdir}}/.git"
