---

- name: Update npm
  become: true
  npm:
    name: npm
    global: true
    state: latest
  when: needs_npm == True

- name: Install packages globally using npm
  become: true
  npm:
    name: "{{item}}"
    state: latest
    global: true
  with_items: "{{ npm_packages |default([]) }}"
  when: needs_npm == True

- name: Install Python modules globally with pip
  become: true
  pip:
    name: "{{item}}"
  with_items: "{{ pip_packages |default([]) }}"
  when: needs_pip == True

- name: Creates files needed before the build
  template:
    source: "files/{{ item.source |default([]) }}"
    dest: "{{ item.dest |default([]) }}"
    mode: "{{ item.mode |default('0644') }}"
  with_items: "{{ pre_build_files }}"
