---
- include: apt-deps.yml
- include: ruby-deps.yml
  when: needs_gem
- include: php-deps.yml
  when: needs_composer
- include: nodejs-deps.yml
  when: needs_npm and not ansible_check_mode # no need to do this if we're not actually going to run the build tasks
- include: python-deps.yml
  when: needs_pip
