---

- name: Add apt repos
  apt_repository:
    repo: "{{item}}"
    update-cache: no
  with_items: apt_repos
  when: apt_repos is defined
  register: update_apt

- name: Update apt cache if necessary
  apt:
    update-cache: yes
    cache_valid_time: 86400
  when: update_apt is defined and update_apt.changed == True

# Task to install deps using apt
# Task to install PHP packages
# Task to install PHP modules
# Task to install pip
# Task to install composer
# Task to install bundler
# Task to install npm
# Task to install deps using pip
# Task to install deps using composer
# Task to install deps using bundler
# Task to install deps using npm
