---

- name: Update npm
  become: true
  npm:
    name: npm
    global: true
    state: latest

- name: Download composer
  become: true
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer

- name: Install composer
  become: true
  shell: cat /tmp/composer | php -- --install-dir=/usr/local/bin
  args:
    creates: /usr/local/bin/composer.phar

- name: Rename composer.phar to composer
  become: true
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
  args:
    creates: /usr/local/bin/composer

- name: Make composer executable
  become: true
  file:
    path: /usr/local/bin/composer
    mode: a+x
    state: file

- name: Check if /usr/bin/ruby and /usr/bin/gem exist
  stat:
    path: "/usr/bin/{{item}}"
  with_items:
    - ruby
    - gem
  register: rs

- name: Find the highest installed ruby and gem versions
  shell: "ls -tr /usr/bin/ | grep -e '^{{item}}' | grep -Eo '[0-9.]{1,7}' |sort -n |tail -1"
  register: rv
  with_items:
    - ruby
    - gem

# This horrendous thing avoids the need to have a separate set tasks for each of ruby and gem
- name: Create /usr/bin/ruby and /usr/bin/gem links if needed
  become: true
  file:
    src: "{{item.0.invocation.module_args.path}}{{item.1.stdout}}"
    dest: "{{item.0.invocation.module_args.path}}"
    state: link
  with_together:
    - "{{rs.results}}"
    - "{{rv.results}}"
  when: item.0.stat.exists == False

- name: Install bundler gem with proper $PATH
  become: true
  gem:
    name: bundler
    state: latest
    user_install: no

- name: Install packages globally using npm
  become: true
  npm:
    name: "{{item}}"
    state: latest
    global: true
  with_items: "{{ npm_packages |default([]) }}"

- name: Install Python modules globally with pip
  become: true
  pip:
    name: "{{item}}"
  with_items: "{{ pip_packages |default([]) }}"

- name: Install user-wide Composer packages
  command: "composer require {{item}}"
  with_items: "{{ composer_packages |default([]) }}"

- name: Add user-wide Composer packages to the system path
  become: true
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: '^PATH='
    line: "PATH={{ansible_env.PATH}}:{{ansible_user_dir}}/vendor/bin"

- name: Add global Composer packages to Ansible's path
  setup:
    filter: ansible_env*

