---

- name: Removes unwanted files or directories
  file:
    path: "{{item}}"
    state: absent
  with_items: "{{ post_build_remove |default([]) }}"

- name: Creates symlinks
  become_user: deploy
  file:
    src: "{{item.source}}"
    dest: "{{item.dest}}"
    state: link
    force: yes
  with_items: "{{ post_build_symlinks |default([]) }}"

# Add files from templates
