---
- include: dependencies.yml
- include: pre-build.yml
- include: checkout.yml
- include: post-checkout.yml
- include: build.yml
  when: not ansible_check_mode
- include: post-build.yml
- include: artefact.yml
