---
- include: apt-deps.yml
- include: ruby-deps.yml
  when: needs_gem == True
- include: php-deps.yml
  when: needs_composer == True
- include: dependencies.yml
- include: pre-build.yml
- include: checkout.yml
- include: post-checkout.yml
- include: tasks.yml
- include: fixup.yml
- include: artefact.yml
