---

- name: Update npm
  become: true
  npm:
    name: npm
    global: true
    state: latest

- name: Install packages globally using npm
  become: true
  npm:
    name: "{{item}}"
    state: latest
    global: true
  with_items: "{{ npm_packages |default([]) }}"
