---

- name: Install dependencies using composer, following composer.lock
  composer:
    command: install
    ignore_platform_reqs: true
    prefer_dist: true
    working_dir: "{{ item | default([]) }}"
  with_items: "{{ composer_local_paths }}"

- name: Install dependencies using bundler, following to Gemfile.lock
  bundler:
    state: present
    chdir: "{{ item | default([]) }}"
  with_items: "{{ gem_local_paths }}"

- name: Install local dependencies using npm, following package.json
  npm:
    path: "{{ item | default([]) }}"
    state: present
  with_items: "{{ npm_local_paths }}"
