---

- name: Download composer
  become: true
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer

- name: Install composer
  become: true
  shell: cat /tmp/composer | php -- --install-dir=/usr/local/bin
  args:
    creates: /usr/local/bin/composer.phar

- name: Rename composer.phar to composer
  become: true
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
  args:
    creates: /usr/local/bin/composer

- name: Make composer executable
  become: true
  file:
    path: /usr/local/bin/composer
    mode: a+x
    state: file

- name: Configures Composer
  command: "composer config --global bin-dir '/usr/local/bin'"

- name: Install system-wide Composer packages
  command: "composer global require {{item}}"
  with_items: "{{ composer_packages |default([]) }}"
