---

- name: Creates files needed post-checkout
  template:
    src: "files/{{ item.source }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode |default('0644') }}"
  with_items: "{{ post_checkout_files |default([]) }}"

- name: Install dependencies using composer, following composer.lock
  composer:
    command: install
    ignore_platform_reqs: true
    prefer_dist: true
    working_dir: "{{ item  }}"
  with_items: "{{ composer_local_paths | default([]) }}"

- name: Install dependencies using bundler, following to Gemfile.lock
  bundler:
    state: present
    chdir: "{{ item }}"
  with_items: "{{ gem_local_paths | default([]) }}"

- name: Install local dependencies using npm, following package.json
  npm:
    path: "{{ item }}"
    state: present
  with_items: "{{ npm_local_paths | default([]) }}"
