---

- name: Removes unwanted files or directories
  file:
    path: "{{item}}"
    state: absent
  with_items: "{{ post_build_remove |default([]) }}"

- name: Creates symlinks
  file:
    src: "{{item.source}}"
    dest: "{{item.dest}}"
    state: link
    force: yes
  with_items: "{{ post_build_symlinks |default([]) }}"

- name: Creates files needed after the build
  template:
    src: "files/{{ item.source }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode |default('0644') }}"
  with_items: "{{ post_build_files |default([]) }}"
