---

- name: Creates files needed before the build
  template:
    source: "files/{{ item.source }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode |default('0644') }}"
  with_items: "{{ pre_build_files |default([]) }}"

- name: Run pre-build tasks
  shell: "{{item}}"
  with_items: "{{ pre_build_commands |default([]) }}"
  register: pre_build_tasks_output

- name: Display pre-build task errors
  debug:
    msg: "{{ item.stderr_lines |default([]) }}"
  with_items: "{{ pre_build_tasks_output.results |default([]) }}"
