---

- name: Creates files needed before the build
  template:
    src: "files/{{ item.source }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode |default('0644') }}"
  with_items: "{{ pre_build_files |default([]) }}"

- name: Run pre-build tasks
  shell: "{{item}}"
  with_items: "{{ pre_build_commands |default([]) }}"
  register: pre_build_tasks_output

- name: Display stderr from failing pre-build tasks
  debug:
    msg: "{{ item.stderr_lines }}"
  with_items: "{{ pre_build_tasks_output.results |selectattr('stderr_lines') |list |default([]) }}"
